### PR TITLE
fixed Berserker button's span text; Berserker class can now be selected

### PR DESCRIPTION
**Pull request by alexsaber89**

### CODE REVIEW

**Comment by ZoeLeBlanc** [comment]
hey I just pulled your code and did you change berserker to lower case? Because now it doesn't work on your branch? Berserker needs to upper case for the GuildHall to work. Let me know if I'm missing something...

**Comment by alexsaber89** [comment]
Hmm, that's the issue I was fixing with this PR.  Was it not lower case for you?  It was showing as lower case for me, which was causing that class to error out when selected.

**Comment by ZoeLeBlanc** [comment]
when I switched to your branch it was showing lowercase which was the cause of the error. Let me check if it's an error with my sublime text not loading

**Comment by ZoeLeBlanc** [comment]
I'm gonna give 👍 since I can see that you made the correct change. Just merge it into master

**Pull request merged**
